### PR TITLE
Fix default value of generateMap setting

### PR DESCRIPTION
**Pull request by StoyanDimitrov**

### CODE REVIEW

**Comment by StoyanDimitrov** [comment]
Well, only in the docs

**Comment by glenn2223** [comment]
Hey @StoyanDimitrov,

The default for `generateMap` is true, as you can see below.

package.json showing the default for generateMap as being true


Are you having an issue with the setting? When it's not set, my sample project is producing the appropriate `map` file

**Comment by StoyanDimitrov** [comment]
True dat! I've done some Live SASS Compiler global settings that have overlooked.

**Comment by glenn2223** [comment]
👍

Glad you found the setting lurking away 😂

**Pull request closed without merging**
