### PR TITLE
Live sass compiler

### PR DESCRIPTION
**Pull request by kevinhehehaha**
[settings.md](https://github.com/user-attachments/files/16924463/settings.md)

### CODE REVIEW

**Comment by glenn2223** [comment]
The ahead branch is now considered stale. New branches are made for updates and feature requests that are then merged into main. Were you meant to merge this into your own fork?

This will be changing slightly with the pre-release/night plans for #365 - but that will have a different branch name

---

For now I'm closing this PR

Continue to comment if you were trying to accomplish something else

**Comment by kevinhehehaha** [comment]
kevinhehehaha:Live-Sass-Compiler

**Comment by kevinhehehaha** [comment]
kevinhehehaha:Live-Sass-Compiler

**Comment by kevinhehehaha** [comment]
[https://github.com/glenn2223/vscode-live-sass-compiler/pull/369](url)

**Pull request closed without merging**
